### ISSUE TITLE
UPDATY: Tlačítka na sdílení?

### ISSUE THREAD

**Issue by kikinna** [mveith/paq-research#16]
Chceme podporovat možnost sdílet jednotlivá témata na soc sítích? 
(Předpokládala bych, že spíš ano).
Prosím, promyslet, co všechno budeme chtít sdílet. Nebo jestli vůbec něco ))

**Comment by MichaelaKudrnacova** [comment]
Přidat tlačítko sdílení na Twitter
=> `co nejdříve`, jak umožní publikace ostatního

**Comment by kikinna** [comment]
Návrh
Dokud se budou tlačítka vlézat, tak by byly na té lištičce a pak by vyskočily pod ten perex). Taky je šance, že bychom je na telefonu trochu pak zvětšily / změnily jim barvu -> to uvidíme ale až po testování

![image](https://user-images.githubusercontent.com/11555522/93989975-d93a1d00-fd8a-11ea-861d-ee769abbd7bd.png)

**Comment by DanProkop** [comment]
Za mne cajk

**Comment by mveith** [comment]
[Je to tam](https://paq-research-5wopmyrnh.vercel.app), můžeme se bavit o drobnostech, ale máme to na preview verzi a až budete chtít, může to do produkce.
