### ISSUE TITLE
UPDATY: Upravit texty: zobecnit základní texty a přidat box "Co je nového"

### ISSUE THREAD

**Issue by MichaelaKudrnacova** [mveith/paq-research#54]
Upravit současné texty, aby byly obecnější a nemusely být s každou vlnou aktualizovány. Přeformulujeme současné texty, aby popisovaly vývoj od března do konce srpna (např. místo formulací „v současnosti“ dáme „na konci letních prázdnin“) či obecné trendy bez aktuáních čísel. ´
Přidá se rámeček „Co je nového od 1. září?“ který bude popisovat aktuální stav, jeho rozdíly oproti stavu na konci prázdnin, případně krátce trend od konce prázdnin do současné vlny – dohromady i zajímavý vývoj u skupin (pokud byl). 
- Kam se rámeček s novinkami dá, jak bude vypadat?

=> publikace `24. září`

**Comment by mveith** [comment]
Vyřešno přes stories.
