### ISSUE TITLE
UPDATY: Přidat novou sekci ukazatelů "Duševní zdraví" (pracovní název)

### ISSUE THREAD

**Issue by MichaelaKudrnacova** [mveith/paq-research#55]
K současným sekcím ukazatelů "Ekonomické dopady" a "Chování a aktivity" přidat sekci "Duševní zdraví" (zatím pracovní název). V ní budou ukazatele:
- Obavy z koronaviru (už dříve nachystaná data pro plochový graf, nestihly se texty pro první publikaci) => publikace `24. září`
- Obavy ze ztráty zaměstnání (analogické jako obavy z koronaviru, plochový graf) => publikace `24. září`
- Stres (zatím nevyjasněné, o co půjde) => publikace `8. října`

**Comment by mveith** [comment]
Hotovo, s tím, že je možné aktualizovat strukturu stránek a stránky se generují dynamicky, je přidání další sránky v pohodě.
