### ISSUE TITLE
UPDATY: Do line chartu prům. počtu kontaktů přidat plochu

### ISSUE THREAD

**Issue by MichaelaKudrnacova** [mveith/paq-research#56]
V line chartu s průměrným počtem kontaktů ukázat plochu s frekvencí kategorie 0–3 kontaktů. Případně i plochy pro 4–10 a 11+ kontaktů, pokud by to dávalo větší smysl a nevypadalo přehlceně.
=> publikace `24. září`

**Comment by mveith** [comment]
Zavírám, bavili jsme se, že půjdeme jinou cestou, v tuhle chvíli by to bylo příliš práce a málo "zisku".
