### ISSUE TITLE
UPDATY: Připravit vlastní zadávání dat pro PAQ

### ISSUE THREAD

**Issue by MichaelaKudrnacova** [mveith/paq-research#58]
Připravit vkládání dat tak, aby si je mohl nahrávat PAQ sám.

=> co `nejdříve`, jak dovolí harmonogram publikací ostatních

**Comment by mveith** [comment]
Vyřešeno přes privátní repo s texty a daty. Doladíme to v průběhu času, zatím to je možný, ale v reálu spíš neproveditelný...
