### ISSUE TITLE
Fix tabulky statistických chyb

### ISSUE THREAD

**Issue by kikinna** [mveith/paq-research#59]
Přidat horizontal scrollbar + volný prostormezi sloupečky

**Comment by mveith** [comment]
Přidal jsem tam minimální šířku těch sloupečků, ale zobrazení scrollbaru je spíš otázka prohlížeče, je tam nastaveno `overflow-x: auto`, takže by se to mělo zobrazit, když je to potřeba (mně se to na mobilním FF zobrazí, když to dostane focus, na desktopu vždycky, když se to tam nevejde...).

**Comment by kikinna** [comment]
Nešlo by nastavit, aby se to na telefonu taky zobrazilo vždy a nejen na focus? (Protože ten vyžaduje uživatelskou akci, ale my potřebujeme, aby to uživatel věděl i bez uživatelské akce)
