### ISSUE TITLE
Přidat radiobuttons k nastavení grafu "Aktivity"

### ISSUE THREAD

**Issue by kikinna** [mveith/paq-research#68]
Nad grafem / grafy týkajících se aktivity podnikaných během pandemie se zobrazí radiobuttons. Uživatel si v radiobuttonech vybírá jednu ze skupin, do kterých jsou organizované aktivity (jedna skupina má cca 5 aktivit)

Pro souhrný graf se zobrazí možnosti A, B, C a D.
Pro small multiples se zobrazí možnosti A, B, C. Tady platí že jedny radiobuttons ovlivňují zobrazení dat ve všech small multiples. 
A: Služby
B: Rodina a cestování
C: Zábava a volný čas
D: Všechny kategorie

Zatím stačí nahodit funkčnost, já klidně doladím design.

**Comment by kikinna** [comment]
@mveith Představím si něco takvého, ale pak to asi ještě budeme muset doladit na místě. 

![image](https://user-images.githubusercontent.com/11555522/94777843-6ea96280-03c4-11eb-99ff-8ca64c4009ad.png)

**Comment by mveith** [comment]
Tak jo, máme tam nějakou [první verzi](https://paq-research-27jtw6tqp.vercel.app/socialni-aktivity).
